version: '2'
services:
  sickrage:
    build: ./sickrage
    labels:
      - traefik.frontend.rule=Host:sickrage.${DOMAIN} 
      - traefik.frontend.entryPoints=http,https
    volumes:
      - ${NZBSDIR}:/mnt/data/downloads/nzbgs
      - ${TORRENTSDIR}:/mnt/data/downloads/torrents
      - ${TVSHOWSDIR}:/mnt/data/tvshows
    networks:
      - seedbox_net
    environment:
      - SICKRAGE_USERNAME=${SICKRAGE_USERNAME}
      - SICKRAGE_PASSWORD=${SICKRAGE_PASSWORD}

  couchpotato:
    build: ./couchpotato
    labels:
      - traefik.frontend.rule=Host:couchpotato.${DOMAIN}
      - traefik.frontend.entryPoints=http,https
    volumes:
      - ${NZBSDIR}:/mnt/data/downloads/nzbs
      - ${TORRENTSDIR}:/mnt/data/downloads/torrents
      - ${MOVIESDIR}:/mnt/data/movies
    networks:
      - seedbox_net

  nzbget:
    build: ./nzbget
    labels:
      - traefik.frontend.rule=Host:nzbget.${DOMAIN}
      - traefik.frontend.entryPoints=http,https
    volumes:
      - ${NZBSDIR}:/mnt/data
    networks:
      - seedbox_net
    environment:
      - NZBGET_USERNAME=${NZBGET_USERNAME}
      - NZBGET_PASSWORD=${NZBGET_PASSWORD}

  transmission:
    build: ./transmission
    labels:
      - traefik.frontend.rule=Host:transmission.${DOMAIN}
      - traefik.frontend.entryPoints=http,https
    volumes:
      - ${TORRENTSDIR}:/mnt/data
    networks:
      - seedbox_net
    environment:
      - TRANSMISSION_USERNAME=${TRANSMISSION_USERNAME}
      - TRANSMISSION_PASSWORD=${TRANSMISSION_PASSWORD}

networks:
  seedbox_net:
    external:
      name: ${SEEDBOX_NETWORK}