version: '2'
services:
  sickrage:
    build: 
      context: ./sickrage
      args:
        DOCKERIZE_ARCH:         ${DOCKERIZE_ARCH}
        SICKRAGE_VERSION:       ${SICKRAGE_VERSION}
    labels:
      - traefik.frontend.rule=Host:sickrage.${DOMAIN} 
      - traefik.frontend.entryPoints=http,https
    restart: always
    volumes:
      - ${NZBSDIR}:/mnt/data/downloads/nzbgs
      - ${TORRENTSDIR}:/mnt/data/downloads/torrents
      - ${TVSHOWSDIR}:/mnt/data/tvshows
    networks:
      - seedbox_net

  couchpotato:
    build: 
      context: ./couchpotato
      args:
        DOCKERIZE_ARCH:         ${DOCKERIZE_ARCH}
        COUCHPOTATO_VERSION:    ${COUCHPOTATO_VERSION}
    labels:
      - traefik.frontend.rule=Host:couchpotato.${DOMAIN}
      - traefik.frontend.entryPoints=http,https
    restart: always
    volumes:
      - ${NZBSDIR}:/mnt/data/downloads/nzbs
      - ${TORRENTSDIR}:/mnt/data/downloads/torrents
      - ${MOVIESDIR}:/mnt/data/movies
    networks:
      - seedbox_net

  nzbget:
    build: 
      context: ./nzbget
      args:
        DOCKERIZE_ARCH:       ${DOCKERIZE_ARCH}
        NZBGET_VERSION:       ${NZBGET_VERSION}
    labels:
      - traefik.frontend.rule=Host:nzbget.${DOMAIN}
      - traefik.frontend.entryPoints=http,https
    restart: always
    volumes:
      - ${NZBSDIR}:/mnt/data
    networks:
      - seedbox_net

  transmission:
    build: 
      context: ./transmission
      args:
        DOCKERIZE_ARCH:         ${DOCKERIZE_ARCH}
    labels:
      - traefik.frontend.rule=Host:transmission.${DOMAIN}
      - traefik.frontend.entryPoints=http,https
    restart: always
    volumes:
      - ${TORRENTSDIR}:/mnt/data
    networks:
      - seedbox_net

networks:
  seedbox_net:
    external:
      name: ${SEEDBOX_NETWORK}