version: '2'
services:
  traefik:
    build: ./traefik
    labels:
      - traefik.enable=false
    networks:
      - traefik_network
    environment:
      - TRAEFIK_DOMAIN=${DOMAIN}
      - TRAEFIK_SUBDOMAINS=${SUBDOMAINS}
      - TRAEFIK_ADMIN_EMAIL=${ADMIN_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik_network:
    external:
      name: traefik_network