version: '2'
services:
  traefik:
    build:
      context: ./traefik
      args:
        DOCKERIZE_ARCH:         ${DOCKERIZE_ARCH}
        TRAEFIK_ARCH:           ${TRAEFIK_ARCH}
    labels:
      - traefik.enable=false
    networks:
      - utilities_network
    environment:
      - TRAEFIK_DOMAIN=${TRAEFIK_DOMAIN}
      - TRAEFIK_SUBDOMAINS=${TRAEFIK_SUBDOMAINS}
      - TRAEFIK_ADMIN_EMAIL=${TRAEFIK_ADMIN_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_DATADIR}:/var/lib/traefik
    ports:
      - ${TRAEFIK_PORT}:80
      - ${TRAEFIK_SECUREPORT}:443
      - ${TRAEFIK_CONTROLPORT}:82
    
networks:
  utilities_network:
    external:
      name: ${UTILITIES_NETWORK}
