version: '2'
services:
  traefik:
    build: ./traefik
    labels:
      - traefik.enable=false
    networks:
      - traefik_network
    environment:
      - TRAEFIK_DOMAIN=${DOMAIN}
      - TRAEFIK_SUBDOMAINS=${SUBDOMAINS}
      - TRAEFIK_ADMIN_EMAIL=${TRAEFIK_ADMIN_EMAIL}
      - TRAEFIK_DATADIR=/var/lib/traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_DATADIR}:/var/lib/traefik
    ports:
      - 80:80
      - 443:443 
    
networks:
  traefik_network:
    external:
      name: traefik_network
