version: '2'
services:
  traefik:
    build:
      context: ./traefik
      args:
        TRAEFIK_INSTALLDIR:     /opt/traefik
        TRAEFIK_CONFDIR:        /etc/traefik
        TRAEFIK_DATADIR:        /var/lib/traefik
        DOCKERIZE_VERSION:      0.2.0
        DOCKERIZE_ARCH:         ${DOCKERIZE_ARCH}
        TRAEFIK_ARCH:           ${TRAEFIK_ARCH}
        TRAEFIK_UID:            1000
        TRAEFIK_GID:            1000
        TRAEFIK_USER:           traefik
        TRAEFIK_GROUP:          traefik
        TRAEFIK_VERSION:        1.0.0-rc2
    labels:
      - traefik.enable=false
    networks:
      - utilities_network
    environment:
      - TRAEFIK_DOMAIN=${TRAEFIK_DOMAIN}
      - TRAEFIK_SUBDOMAINS=${TRAEFIK_SUBDOMAINS}
      - TRAEFIK_ADMIN_EMAIL=${TRAEFIK_ADMIN_EMAIL}
      - TRAEFIK_PORT=${TRAEFIK_PORT}
      - TRAEFIK_SECUREPORT=${TRAEFIK_SECUREPORT}
      - TRAEFIK_CONTROLPORT=${TRAEFIK_CONTROLPORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_DATADIR}:/var/lib/traefik
    ports:
      - ${TRAEFIK_PORT}:${TRAEFIK_PORT}
      - ${TRAEFIK_SECUREPORT}:${TRAEFIK_SECUREPORT}
      - ${TRAEFIK_CONTROLPORT}:${TRAEFIK_CONTROLPORT}
    
networks:
  utilities_network:
    external:
      name: ${UTILITIES_NETWORK}
