version: '2'
services:
  seafile:
    image: seafile:latest
    labels:
      - traefik.frontend.rule=Host:${SEAFILE_HOSTNAME}
      - traefik.frontend.entryPoints=http,https
    hostname: ${SEAFILE_HOSTNAME}
    networks:
      - cloudbox_network
    environment:
      - SEAFILE_HOSTNAME=${SEAFILE_HOSTNAME}
      - SEAFILE_SERVERNAME=${SEAFILE_SERVERNAME}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}

      - SEAFILE_SMTP_SERVER=${SEAFILE_SMTP_SERVER}
      - SEAFILE_SMTP_EMAIL=${SEAFILE_SMTP_EMAIL}
      - SEAFILE_SMTP_PASSWORD=${SEAFILE_SMTP_PASSWORD}
    restart: always
    volumes:
      - ${SEAFILE_DATADIR}:/var/lib/seafile

networks:
  cloudbox_network:
    external:
      name: ${CLOUDBOX_NETWORK}
