version: '2'
services:
  seafile:
    build: 
      context: ./seafile
      args:
        SEAFILE_INSTALLDIR:     /opt/seafile
        SEAFILE_DATADIR:        /var/lib/seafile
        DOCKERIZE_VERSION:      0.2.0
        DOCKERIZE_ARCH:         ${DOCKERIZE_ARCH}
        SEAFILE_UID:            1000
        SEAFILE_GID:            1000
        SEAFILE_USER:           seafile
        SEAFILE_GROUP:          seafile
        SEAFILE_VERSION:        5.1.3
        SEAFILE_URL:            ${SEAFILE_URL}
        SEAFILE_SEAHUB_PORT:    8000     
        SEAFILE_SERVER_PORT:    8082
    labels:
      - traefik.frontend.rule=Host:${SEAFILE_HOSTNAME}
      - traefik.frontend.entryPoints=http,https
    networks:
      - cloudbox_network
    environment:
      - SEAFILE_PORT=${SEAFILE_PORT}
      - SEAFILE_HOSTNAME=${SEAFILE_HOSTNAME}
      - SEAFILE_SERVERNAME=${SEAFILE_SERVERNAME}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
    volumes:
      - ${SEAFILE_DATADIR}:/var/lib/seafile

networks:
  cloudbox_network:
    external:
      name: ${CLOUDBOX_NETWORK}
