FROM {{.Env.BASE_IMAGE}}
MAINTAINER Alexandre ACEBEDO

ARG TRAEFIK_INSTALLDIR=/opt/traefik
ARG TRAEFIK_CONFDIR=/etc/traefik
ARG TRAEFIK_DATADIR=/var/lib/traefik

ARG TRAEFIK_VERSION=1.0.0-rc2

ARG TRAEFIK_USER=traefik
ARG TRAEFIK_UID=1000

ARG TRAEFIK_GROUP=traefik
ARG TRAEFIK_GID=1000

ARG DOCKERIZE_VERSION=0.2.0
ARG DOCKERIZE_ARCH=amd64

ARG TRAEFIK_ARCH=amd64

ARG TRAEFIK_PORT=80
ARG TRAEFIK_SECUREPORT=443
ARG TRAEFIK_CONTROLPORT=82

ENV TRAEFIK_ADMIN_EMAIL  root@domain.com
ENV TRAEFIK_DOMAIN       example.domain.com
ENV TRAEFIK_SUBDOMAINS   ""

RUN apk update
RUN apk add git zsh openssl ca-certificates vim libcap

RUN addgroup -g ${TRAEFIK_GID} -S ${TRAEFIK_GROUP}
RUN adduser -G ${TRAEFIK_GROUP} -u ${TRAEFIK_UID} -S -H ${TRAEFIK_USER} 

RUN mkdir -p ${TRAEFIK_INSTALLDIR}
RUN mkdir -p ${TRAEFIK_CONFDIR}
RUN mkdir -p ${TRAEFIK_DATADIR}

RUN wget https://github.com/containous/traefik/releases/download/v${TRAEFIK_VERSION}/traefik_linux-${TRAEFIK_ARCH} -O ${TRAEFIK_INSTALLDIR}/traefik

RUN wget https://github.com/aacebedo/dockerize/releases/download/v${DOCKERIZE_VERSION}/dockerize-linux-${DOCKERIZE_ARCH}-v${DOCKERIZE_VERSION}.tar.gz -O /tmp/dockerize.tar.gz
RUN tar -C /usr/local/bin -xzvf /tmp/dockerize.tar.gz
RUN rm /tmp/dockerize.tar.gz

COPY ./files/traefik.conf.tmpl ${TRAEFIK_CONFDIR}/traefik.conf.tmpl

COPY files/entrypoint.sh.tmpl ${TRAEFIK_INSTALLDIR}/entrypoint.sh.tmpl
RUN dockerize -template ${TRAEFIK_INSTALLDIR}/entrypoint.sh.tmpl:${TRAEFIK_INSTALLDIR}/entrypoint.sh

RUN chown -R ${TRAEFIK_USER}:${TRAEFIK_GROUP} ${TRAEFIK_CONFDIR}
RUN chown -R ${TRAEFIK_USER}:${TRAEFIK_GROUP} ${TRAEFIK_DATADIR}
RUN chown -R ${TRAEFIK_USER}:${TRAEFIK_GROUP} ${TRAEFIK_INSTALLDIR}
RUN chmod a+x ${TRAEFIK_INSTALLDIR}/traefik
RUN chmod u+x ${TRAEFIK_INSTALLDIR}/entrypoint.sh

RUN setcap 'cap_net_bind_service=+ep' ${TRAEFIK_INSTALLDIR}/traefik

EXPOSE ${TRAEFIK_PORT} ${TRAEFIK_SECUREPORT} ${TRAEFIK_CONTROLPORT}

USER ${TRAEFIK_USER}

VOLUME ["unix:///var/run/docker.sock"]

WORKDIR ${TRAEFIK_INSTALLDIR}

ENTRYPOINT ["./entrypoint.sh"]
