FROM {{.Env.BaseImage}}

RUN apk add --no-cache ca-certificates

ARG CFDNSUPDATER_INSTALLDIR=/opt/cfdnsupdater
ARG CFDNSUPDATER_CONFDIR=/etc/
ARG CFDNSUPDATER_DATADIR=/var/lib/cfdnsupdater

ARG CFDNSUPDATER_VERSION=0.9.1
ARG CFDNSUPDATER_URL=https://github.com/aacebedo/cfdnsupdater/releases/download/${CFDNSUPDATER_VERSION}/cfdnsupdater.arm.${CFDNSUPDATER_DATADIRVERSION}.tar /tmp/cfdnsupdater.tar

ARG DOCKERIZE_VERSION=0.2.0
ARG DOCKERIZE_ARCH=amd64
ARG DOCKERIZE_URL=https://github.com/aacebedo/dockerize/releases/download/v${DOCKERIZE_VERSION}/dockerize-linux-${DOCKERIZE_ARCH}-v${DOCKERIZE_VERSION}.tar.gz -O /tmp/dockerize.tar.gz

RUN wget ${DOCKERIZE_URL} -O /tmp/dockerize.tar.gz
RUN tar -C /usr/local/bin -xzvf /tmp/dockerize.tar.gz
RUN rm /tmp/dockerize.tar.gz

ADD ${CFDNSUPDATER_URL} /tmp/cfdnsupdater.tar
RUN tar xvf /tmp/cfdnsupdater.tar -C /
RUN rm -rf /tmp/cfdnsupdater.tar

COPY ./files/cfdnsupdater.conf.tmpl ${CFDNSUPDATER_CONFDIR}/cfdnsupdater.conf.tmpl

ENTRYPOINT ["zsh", "-c", "dockerize -template ${CFDNSUPDATER_CONFDIR}/cfdnsupdater.conf.tmpl:${CFDNSUPDATER_CONFDIR}/cfdnsupdater.conf ${CFDNSUPDATER_INSTALLDIR}/cfdnsupdater -c ${CFDNSUPDATER_CONFDIR/cfdnsupdater.conf"]


