FROM ubuntu:latest
MAINTAINER Alexandre ACEBEDO

ARG SEAFILE_INSTALLDIR=/opt/seafile
ARG SEAFILE_DATADIR=/var/lib/seafile

ARG SEAFILE_VERSION=5.1.3

ARG SEAFILE_URL=https://bintray.com/artifact/download/seafile-org/seafile/seafile-server_${SEAFILE_VERSION}_x86-64.tar.gz

ARG SEAFILE_USER=seafile
ARG SEAFILE_UID=1000
ARG SEAFILE_GROUP=seafile
ARG SEAFILE_GID=1000

ARG DOCKERIZE_VERSION=0.2.0
ARG DOCKERIZE_ARCH=amd64

ARG SEAFILE_SEAHUB_PORT=8000
ARG SEAFILE_SERVER_PORT=8082

ARG SEAFILE_PORT=80

ENV SEAFILE_SERVERNAME     seafile
ENV SEAFILE_HOSTNAME       seafile.example.com

ENV SEAFILE_ADMIN_EMAIL    admin@example.com
ENV SEAFILE_ADMIN_PASSWORD password

RUN apt update 
RUN apt install lighttpd python python-pip python-imaging python3 sqlite gcc python-pillow \
    python-dev libssl-dev libldap2-dev zsh less vim bash libevent-dev zlib1g-dev \
    libglib2.0-dev libffi-dev libjansson4 libsasl2-dev wget python3-pip -y --force-yes
RUN pip install python-ldap
RUN pip3 install --upgrade pip
RUN pip3 install pexpect

RUN addgroup --system --gid ${SEAFILE_GID} ${SEAFILE_GROUP}
RUN adduser --system -gid ${SEAFILE_GID} --uid ${SEAFILE_UID} ${SEAFILE_USER} 

RUN mkdir -p ${SEAFILE_INSTALLDIR}
RUN mkdir -p ${SEAFILE_DATADIR}

RUN wget https://github.com/aacebedo/dockerize/releases/download/v${DOCKERIZE_VERSION}/dockerize-linux-${DOCKERIZE_ARCH}-v${DOCKERIZE_VERSION}.tar.gz -O /tmp/dockerize.tar.gz
RUN tar -C /usr/local/bin -xzvf /tmp/dockerize.tar.gz
RUN rm -rf /tmp/dockerize.tar.gz

COPY files/entrypoint.sh.tmpl ${SEAFILE_INSTALLDIR}/entrypoint.sh.tmpl
RUN dockerize -template ${SEAFILE_INSTALLDIR}/entrypoint.sh.tmpl:${SEAFILE_INSTALLDIR}/entrypoint.sh

COPY files/seafile-installer.py ${SEAFILE_INSTALLDIR}/seafile-installer.py
COPY files/ccnet.conf.tmpl ${SEAFILE_INSTALLDIR}/ccnet.conf.tmpl
COPY files/seahub_settings.py.tmpl ${SEAFILE_INSTALLDIR}/seahub_settings.py.tmpl
COPY files/lighttpd.conf.tmpl ${SEAFILE_INSTALLDIR}/lighttpd.conf.tmpl

RUN wget ${SEAFILE_URL} -O /tmp/seafile.tar.gz

RUN chmod u+x ${SEAFILE_INSTALLDIR}/entrypoint.sh
RUN chmod u+x ${SEAFILE_INSTALLDIR}/seafile-installer.py

RUN chown -R ${SEAFILE_USER}:${SEAFILE_GROUP} ${SEAFILE_INSTALLDIR}
RUN chown -R ${SEAFILE_USER}:${SEAFILE_GROUP} ${SEAFILE_DATADIR}
RUN chown -R ${SEAFILE_USER}:${SEAFILE_GROUP} ${SEAFILE_DATADIR}

RUN setcap 'cap_net_bind_service=+ep' `which lighttpd`
#RUN setcap 'cap_net_bind_service=+ep' ${SEAFILE_INSTALLDIR}/seafile-server-${SEAFILE_VERSION}/seafile.sh
#RUN setcap 'cap_net_bind_service=+ep' ${SEAFILE_INSTALLDIR}/seafile-server-${SEAFILE_VERSION}/seahub.sh

EXPOSE ${SEAFILE_PORT}

USER ${SEAFILE_USER}
WORKDIR ${SEAFILE_INSTALLDIR}

ENTRYPOINT ["./entrypoint.sh"]