FROM {{.Env.BASE_IMAGE}}
MAINTAINER Alexandre ACEBEDO

ENV SICKRAGE_INSTALLDIR   /opt/sickrage
ENV SICKRAGE_CONFDIR      /etc/sickrage
ENV SICKRAGE_DATADIR      /var/lib/sickrage

ENV SICKRAGE_USER         sickrage

ARG SICKRAGE_USERNAME
ENV SICKRAGE_USERNAME     ${SICKRAGE_USERNAME:-admin}

ARG SICKRAGE_PASSWORD
ENV SICKRAGE_PASSWORD     ${SICKRAGE_PASSWORD:-password}

ARG SICKRAGE_UID
ENV SICKRAGE_UID          ${SICKRAGE_UID:-1000}

ENV SICKRAGE_GROUP        sickrage

ARG SICKRAGE_GID
ENV SICKRAGE_GID          ${SICKRAGE_GID:-1000}

ARG SICKRAGE_PORT
ENV SICKRAGE_PORT         ${SICKRAGE_PORT:-80}
 
ARG SICKRAGE_VERSION
ENV SICKRAGE_VERSION      ${SICKRAGE_VERSION:-2016.05.20-1}

ENV DOCKERIZE_VERSION     0.2.0
ENV DOCKERIZE_ARCH        {{.Env.DOCKERIZE_ARCH}}

RUN apk update
RUN apk add git unzip python unrar wget tar zsh openssl py-openssl vim ca-certificates libcap

RUN wget https://github.com/SickRage/SickRage/archive/${SICKRAGE_VERSION}.tar.gz -O /tmp/sickrage.tar.gz
RUN mkdir -p ${SICKRAGE_INSTALLDIR}
RUN tar --strip-components=1  -C ${SICKRAGE_INSTALLDIR} -xvzf /tmp/sickrage.tar.gz
RUN rm -rf /tmp/sickrage.tar.gz

RUN wget https://github.com/jwilder/dockerize/releases/download/v${DOCKERIZE_VERSION}/dockerize-linux-${DOCKERIZE_ARCH}-v${DOCKERIZE_VERSION}.tar.gz -O /tmp/dockerize.tar.gz
RUN tar -C /usr/local/bin -xzvf /tmp/dockerize.tar.gz
RUN rm /tmp/dockerize.tar.gz

RUN addgroup -g ${SICKRAGE_GID} -S ${SICKRAGE_GROUP}
RUN adduser -G ${SICKRAGE_GROUP} -u ${SICKRAGE_UID} -S -H ${SICKRAGE_USER} 

RUN mkdir -p ${SICKRAGE_CONFDIR}
COPY ./files/settings.conf.tmpl ${SICKRAGE_CONFDIR}/settings.conf.tmpl
RUN chown -R ${SICKRAGE_USER}:${SICKRAGE_GROUP} ${SICKRAGE_CONFDIR}

RUN mkdir -p ${SICKRAGE_DATADIR}
RUN chown -R ${SICKRAGE_USER}:${SICKRAGE_GROUP} ${SICKRAGE_DATADIR}

RUN chown -R ${SICKRAGE_USER}:${SICKRAGE_GROUP} ${SICKRAGE_INSTALLDIR}
 
RUN setcap 'cap_net_bind_service=+ep' ${SICKRAGE_INSTALLDIR}/SickBeard.py

VOLUME [${SICKRAGE_DATADIR}] 
EXPOSE ${SICKRAGE_PORT}
USER ${SICKRAGE_GUSER} 

WORKDIR ${SICKRAGE_INSTALLDIR}

ENTRYPOINT ["zsh", "-c", "dockerize -template ${SICKRAGE_CONFDIR}/settings.conf.tmpl:${SICKRAGE_CONFDIR}/settings.conf ./SickBeard.py --datadir=${SICKRAGE_DATADIR} --config=${SICKRAGE_CONFDIR}/settings.conf"]
