FROM {{.Env.BASE_IMAGE}}
MAINTAINER Alexandre ACEBEDO

ARG SICKRAGE_INSTALLDIR=/opt/sickrage
ARG SICKRAGE_CONFDIR=/etc/sickrage
ARG SICKRAGE_DATADIR=/var/lib/sickrage

ARG SICKRAGE_VERSION=2016.05.20-1

ARG DOCKERIZE_VERSION=0.2.0
ARG DOCKERIZE_ARCH=amd64

ARG SICKRAGE_USER=sickrage
ARG SICKRAGE_UID=1000

ARG SICKRAGE_GROUP=sickrage
ARG SICKRAGE_GID=1000

ARG SICKRAGE_PORT=80

ENV SICKRAGE_USERNAME     admin
ENV SICKRAGE_PASSWORD     password

RUN apk update
RUN apk add git unzip python unrar wget tar zsh openssl py-openssl vim ca-certificates libcap

RUN addgroup -g ${SICKRAGE_GID} -S ${SICKRAGE_GROUP}
RUN adduser -G ${SICKRAGE_GROUP} -u ${SICKRAGE_UID} -S -H ${SICKRAGE_USER} 

RUN mkdir -p ${SICKRAGE_INSTALLDIR}
RUN mkdir -p ${SICKRAGE_CONFDIR}
RUN mkdir -p ${SICKRAGE_DATADIR}

RUN wget https://github.com/SickRage/SickRage/archive/${SICKRAGE_VERSION}.tar.gz -O /tmp/sickrage.tar.gz
RUN tar --strip-components=1  -C ${SICKRAGE_INSTALLDIR} -xvzf /tmp/sickrage.tar.gz
RUN rm -rf /tmp/sickrage.tar.gz

RUN wget https://github.com/aacebedo/dockerize/releases/download/v${DOCKERIZE_VERSION}/dockerize-linux-${DOCKERIZE_ARCH}-v${DOCKERIZE_VERSION}.tar.gz -O /tmp/dockerize.tar.gz
RUN tar -C /usr/local/bin -xzvf /tmp/dockerize.tar.gz
RUN rm /tmp/dockerize.tar.gz

COPY ./files/entrypoint.sh.tmpl ${SICKRAGE_INSTALLDIR}/entrypoint.sh.tmpl
RUN dockerize -template ${SICKRAGE_INSTALLDIR}/entrypoint.sh.tmpl:${SICKRAGE_INSTALLDIR}/entrypoint.sh

COPY ./files/settings.conf.tmpl ${SICKRAGE_CONFDIR}/settings.conf.tmpl

RUN chown -R ${SICKRAGE_USER}:${SICKRAGE_GROUP} ${SICKRAGE_CONFDIR}
RUN chown -R ${SICKRAGE_USER}:${SICKRAGE_GROUP} ${SICKRAGE_DATADIR}
RUN chown -R ${SICKRAGE_USER}:${SICKRAGE_GROUP} ${SICKRAGE_INSTALLDIR}

RUN chmod u+x ${SICKRAGE_INSTALLDIR}/entrypoint.sh
 
RUN setcap 'cap_net_bind_service=+ep' /usr/bin/python2.7

VOLUME [${SICKRAGE_DATADIR}]

EXPOSE ${SICKRAGE_PORT}

USER ${SICKRAGE_USER} 

WORKDIR ${SICKRAGE_INSTALLDIR}

ENTRYPOINT ["./entrypoint.sh"]
