FROM {{.Env.BASE_IMAGE}}

RUN apk update
RUN apk add tzdata libcap zsh vim ca-certificates wget

ARG TIMEZONE=Europe/Paris

ARG DNSDOCK_INSTALLDIR=/opt/dnsdock

ARG DNSDOCK_VERSION=1.12.1
ARG DNSDOCK_ARCH=amd64
ARG DNSDOCK_URL=https://github.com/aacebedo/dnsdock/releases/download/${DNSDOCK_VERSION}/dnsdock.${DNSDOCK_ARCH}.${DNSDOCK_VERSION}.tar.gz

ARG DOCKERIZE_VERSION=0.2.0
ARG DOCKERIZE_ARCH=amd64
ARG DOCKERIZE_URL=https://github.com/aacebedo/dockerize/releases/download/v${DOCKERIZE_VERSION}/dockerize-linux-${DOCKERIZE_ARCH}-v${DOCKERIZE_VERSION}.tar.gz
ARG DOCKERIZE_INSTALLDIR=/opt/dockerize

ARG DNSDOCK_USER=DNSDOCK
ARG DNSDOCK_UID=1000
ARG DNSDOCK_GROUP=DNSDOCK
ARG DNSDOCK_GID=1000

ENV DNSDOCK_DOMAIN      example.com

ENV LC_ALL en_US.utf8

RUN cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
RUN echo "${TIMEZONE}" > /etc/timezone

RUN addgroup -g ${DNSDOCK_GID} -S ${DNSDOCK_GROUP}
RUN adduser -G ${DNSDOCK_GROUP} -u ${DNSDOCK_UID} -S -H ${DNSDOCK_USER} 

RUN mkdir -p ${DOCKERIZE_INSTALLDIR}
RUN mkdir -p ${DNSDOCK_INSTALLDIR}

RUN wget ${DOCKERIZE_URL} -O /tmp/dockerize.tar.gz
RUN tar -xzvf /tmp/dockerize.tar.gz -C ${DOCKERIZE_INSTALLDIR}
RUN rm /tmp/dockerize.tar.gz

RUN wget ${DNSDOCK_URL} -O /tmp/dnsdock.tar.gz
RUN tar -xvzf /tmp/dnsdock.tar.gz -C ${DNSDOCK_INSTALLDIR} 
RUN rm -rf /tmp/dnsdock.tar.gz

COPY files/entrypoint.sh.tmpl ${DNSDOCK_INSTALLDIR}/entrypoint.sh.tmpl
RUN ${DOCKERIZE_INSTALLDIR}/dockerize -template ${DNSDOCK_INSTALLDIR}/entrypoint.sh.tmpl:${DNSDOCK_INSTALLDIR}/entrypoint.sh

RUN chown -R ${DNSDOCK_USER}:${DNSDOCK_GROUP} ${DNSDOCK_INSTALLDIR}
RUN chown -R ${DNSDOCK_USER}:${DNSDOCK_GROUP} ${DOCKERIZE_INSTALLDIR}

RUN chmod u+x ${DNSDOCK_INSTALLDIR}/entrypoint.sh
RUN setcap 'cap_net_bind_service=+ep' ${DNSDOCK_INSTALLDIR}/dnsdock

USER ${DNSDOCK_USER}

WORKDIR ${DNSDOCK_INSTALLDIR}

ENTRYPOINT ["./entrypoint.sh"]
