version: '2'
services:
  ghost:
    build: ./ghost
    labels:
      - traefik.frontend.rule=Host:blog.${DOMAIN} 
      - traefik.frontend.entryPoints=http,https
    networks:
      - blogbox_network
    environment:
      - GHOST_URL=https://blog.${DOMAIN}
    volumes:
      - ${GHOST_DATADIR}:/var/lib/ghost

networks:
  blogbox_network:
    external:
      name: ${BLOGBOX_NETWORK}
    
