version: '2'
services:
  ghost:
    environment:
      GHOST_URL: https://blog.${DOMAIN}
    build: ./ghost
    labels:
      - traefik.frontend.rule=Host:blog.${DOMAIN} 
      - traefik.frontend.entryPoints=http,https
    networks:
      - trafiek_network
networks:
  trafiek_network:
    external:
      name: traefik_network
    
