FROM {{.Env.BASE_IMAGE}}
MAINTAINER Alexandre ACEBEDO

RUN apk update
RUN apk add git unzip unrar wget vim tar zsh openssl transmission transmission-daemon ca-certificates libcap

ARG TRANSMISSION_INSTALLDIR=/usr/loca/bin
ARG TRANSMISSION_DATADIR=/var/lib/transmission
ARG TRANSMISSION_CONFDIR=/etc/transmission

ARG TRANSMISSION_USER=transmission
ARG TRANSMISSION_UID=1000

ARG TRANSMISSION_GROUP=transmission
ARG TRANSMISSION_GID=1000

ARG DOCKERIZE_VERSION=0.2.0
ARG DOCKERIZE_ARCH=amd64
ARG DOCKERIZE_URL=https://github.com/aacebedo/dockerize/releases/download/v${DOCKERIZE_VERSION}/dockerize-linux-${DOCKERIZE_ARCH}-v${DOCKERIZE_VERSION}.tar.gz
ARG DOCKERIZE_INSTALLDIR=/opt/dockerize

ARG TRANSMISSION_PORT=80

ENV TRANSMISSION_USERNAME   admin
ENV TRANSMISSION_PASSWORD   password

RUN addgroup -g ${TRANSMISSION_GID} -S ${TRANSMISSION_GROUP} | true
RUN adduser -G ${TRANSMISSION_GROUP} -u ${TRANSMISSION_UID} -S -H ${TRANSMISSION_USER} | true

RUN mkdir -p ${TRANSMISSION_CONFDIR}
RUN mkdir -p ${TRANSMISSION_INSTALLDIR}
RUN mkdir -p ${DOCKERIZE_INSTALLDIR}

RUN rm -rf /usr/share/transmission/web
RUN git clone https://github.com/endor/kettu.git /usr/share/transmission/web

RUN wget ${DOCKERIZE_URL} -O /tmp/dockerize.tar.gz
RUN tar -xzvf /tmp/dockerize.tar.gz -C ${DOCKERIZE_INSTALLDIR}
RUN rm -rf /tmp/dockerize.tar.gz

COPY ./files/settings.json.tmpl ${TRANSMISSION_INSTALLDIR}/settings.json.tmpl

COPY ./files/entrypoint.sh.tmpl ${TRANSMISSION_INSTALLDIR}/entrypoint.sh.tmpl
RUN ${DOCKERIZE_INSTALLDIR}/dockerize -template ${TRANSMISSION_INSTALLDIR}/entrypoint.sh.tmpl:${TRANSMISSION_INSTALLDIR}/entrypoint.sh

RUN chown -R ${TRANSMISSION_USER}:${TRANSMISSION_GROUP} ${TRANSMISSION_CONFDIR}
RUN chown ${TRANSMISSION_USER}:${TRANSMISSION_GROUP} ${TRANSMISSION_INSTALLDIR}/entrypoint.sh
RUN chown -R ${TRANSMISSION_USER}:${TRANSMISSION_GROUP} ${DOCKERIZE_INSTALLDIR}

RUN chmod u+x ${TRANSMISSION_INSTALLDIR}/entrypoint.sh

RUN setcap 'cap_net_bind_service=+ep' `which transmission-daemon`

EXPOSE ${TRANSMISSION_PORT}

USER ${TRANSMISSION_USER} 

WORKDIR ${TRANSMISSION_INSTALLDIR}

ENTRYPOINT ["./entrypoint.sh"]