FROM {{.Env.BASE_IMAGE}}
MAINTAINER Alexandre ACEBEDO

RUN apk update
RUN apk add git unzip python unrar wget tar zsh openssl py-openssl ca-certificates py-cryptography py-enum34 py-cffi py-lxml vim libcap

ARG COUCHPOTATO_INSTALLDIR=/opt/couchpotato
ARG COUCHPOTATO_CONFDIR=/etc/couchpotato
ARG COUCHPOTATO_DATADIR=/var/lib/couchpotato

ARG COUCHPOTATO_VERSION=3.0.1
ARG COUCHPOTATO_URL=https://github.com/CouchPotato/CouchPotatoServer/archive/build/${COUCHPOTATO_VERSION}.tar.gz

ARG COUCHPOTATO_USER=couchpotato
ARG COUCHPOTATO_UID=1000
ARG COUCHPOTATO_GROUP=couchpotato
ARG COUCHPOTATO_GID=1000

ARG DOCKERIZE_VERSION=0.2.0
ARG DOCKERIZE_ARCH=amd64
ARG DOCKERIZE_URL=https://github.com/aacebedo/dockerize/releases/download/v${DOCKERIZE_VERSION}/dockerize-linux-${DOCKERIZE_ARCH}-v${DOCKERIZE_VERSION}.tar.gz

ARG COUCHPOTATO_PORT=80

RUN addgroup -g ${COUCHPOTATO_GID} -S ${COUCHPOTATO_GROUP}
RUN adduser -G ${COUCHPOTATO_GROUP} -u ${COUCHPOTATO_UID} -S -H ${COUCHPOTATO_USER} 

RUN mkdir -p ${COUCHPOTATO_CONFDIR}
RUN mkdir -p ${COUCHPOTATO_DATADIR}
RUN mkdir -p ${COUCHPOTATO_INSTALLDIR}

RUN wget ${COUCHPOTATO_URL} -O /tmp/couchpotato.tar.gz
RUN tar --strip-components=1  -C ${COUCHPOTATO_INSTALLDIR} -xvzf /tmp/couchpotato.tar.gz
RUN rm -rf /tmp/couchpotato.tar.gz

RUN wget ${DOCKERIZE_URL} -O /tmp/dockerize.tar.gz
RUN tar -C /usr/local/bin -xzvf /tmp/dockerize.tar.gz
RUN rm -rf /tmp/dockerize.tar.gz

COPY ./files/settings.conf.tmpl ${COUCHPOTATO_CONFDIR}/settings.conf.tmpl

COPY ./files/entrypoint.sh.tmpl ${COUCHPOTATO_INSTALLDIR}/entrypoint.sh.tmpl
RUN dockerize -template ${COUCHPOTATO_INSTALLDIR}/entrypoint.sh.tmpl:${COUCHPOTATO_INSTALLDIR}/entrypoint.sh

RUN chown -R ${COUCHPOTATO_USER}:${COUCHPOTATO_GROUP} ${COUCHPOTATO_CONFDIR}
RUN chown -R ${COUCHPOTATO_USER}:${COUCHPOTATO_GROUP} ${COUCHPOTATO_DATADIR}
RUN chown -R ${COUCHPOTATO_USER}:${COUCHPOTATO_GROUP} ${COUCHPOTATO_INSTALLDIR} 

RUN chmod u+x ${COUCHPOTATO_INSTALLDIR}/entrypoint.sh

RUN setcap 'cap_net_bind_service=+ep' /usr/bin/python2.7

EXPOSE ${COUCHPOTATO_PORT}

VOLUME [${COUCHPOTATO_DATADIR}]

USER ${COUCHPOTATO_USER}

WORKDIR ${COUCHPOTATO_INSTALLDIR}

ENTRYPOINT ["./entrypoint.sh"]