FROM {{.Env.BASE_IMAGE}}
MAINTAINER Alexandre ACEBEDO

RUN apk update
RUN apk add tzdata wget ca-certificates zsh vim libcap

ARG TIMEZONE=Europe/Paris

ARG NZBGET_INSTALLDIR=/opt/nzbget
ARG NZBGET_CONFDIR=/etc/nzbget
ARG NZBGET_DATADIR=/var/lib/nzbget

ARG NZBGET_USER=nzbget
ARG NZBGET_UID=1000

ARG NZBGET_GROUP=nzbget
ARG NZBGET_GID=1000

ARG NZBGET_VERSION=16.4
ARG NZBGET_URL=https://github.com/nzbget/nzbget/releases/download/v${NZBGET_VERSION}/nzbget-${NZBGET_VERSION}-bin-linux.run 

ARG DOCKERIZE_VERSION=0.2.0
ARG DOCKERIZE_ARCH=amd64
ARG DOCKERIZE_URL=https://github.com/aacebedo/dockerize/releases/download/v${DOCKERIZE_VERSION}/dockerize-linux-${DOCKERIZE_ARCH}-v${DOCKERIZE_VERSION}.tar.gz
ARG DOCKERIZE_INSTALLDIR=/opt/dockerize

ARG NZBGET_PORT=80

ENV NZBGET_USERNAME    admin
ENV NZBGET_PASSWORD    password

ENV TERM xterm

RUN cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
RUN echo "${TIMEZONE}" > /etc/timezone

RUN addgroup -g ${NZBGET_GID} -S ${NZBGET_GROUP}
RUN adduser -G ${NZBGET_GROUP} -u ${NZBGET_UID} -S -H ${NZBGET_USER} 

RUN mkdir -p ${NZBGET_INSTALLDIR}
RUN mkdir -p ${NZBGET_CONFDIR}
RUN mkdir -p ${NZBGET_DATADIR}
RUN mkdir -p ${DOCKERIZE_INSTALLDIR}

RUN wget ${NZBGET_URL} -O /tmp/nzbget.bin
RUN chmod a+x /tmp/nzbget.bin
RUN /tmp/nzbget.bin --destdir ${NZBGET_INSTALLDIR} 

RUN wget ${DOCKERIZE_URL} -O /tmp/dockerize.tar.gz
RUN tar -xzvf /tmp/dockerize.tar.gz -C ${DOCKERIZE_INSTALLDIR}
RUN rm /tmp/dockerize.tar.gz



COPY ./files/nzbget.conf.tmpl ${NZBGET_INSTALLDIR}/nzbget.conf.tmpl
WORKDIR ${NZBGET_INSTALLDIR}
RUN ${DOCKERIZE_INSTALLDIR}/dockerize -force -delims "<@:@>" -template ./nzbget.conf.tmpl:./nzbget.conf.tmpl


COPY ./files/entrypoint.sh.tmpl ${NZBGET_INSTALLDIR}/entrypoint.sh.tmpl
RUN ${DOCKERIZE_INSTALLDIR}/dockerize -template ${NZBGET_INSTALLDIR}/entrypoint.sh.tmpl:${NZBGET_INSTALLDIR}/entrypoint.sh

RUN chown -R ${NZBGET_USER}:${NZBGET_GROUP} ${NZBGET_CONFDIR}
RUN chown -R ${NZBGET_USER}:${NZBGET_GROUP} ${NZBGET_DATADIR}
RUN chown -R ${NZBGET_USER}:${NZBGET_GROUP} ${NZBGET_INSTALLDIR}
RUN chown -R ${NZBGET_USER}:${NZBGET_GROUP} ${DOCKERIZE_INSTALLDIR}

RUN chmod u+x ${NZBGET_INSTALLDIR}/entrypoint.sh

RUN setcap 'cap_net_bind_service=+ep' ${NZBGET_INSTALLDIR}/nzbget

VOLUME [${NZBGET_DATADIR}]

EXPOSE ${NZBGET_PORT}

USER ${NZBGET_USER}

WORKDIR ${NZBGET_INSTALLDIR} 

ENTRYPOINT ["./entrypoint.sh"]
