FROM {{.Env.BASE_IMAGE}}
MAINTAINER Alexandre ACEBEDO

ENV NZBGET_INSTALLDIR  /opt/nzbget
ENV NZBGET_CONFDIR     /etc/nzbget
ENV NZBGET_DATADIR     /var/lib/nzbget

ENV NZBGET_USER        nzbget

ARG NZBGET_UID
ENV NZBGET_UID         ${NZBGET_UID:-1000}

ENV NZBGET_GROUP       nzbget

ARG NZBGET_GID
ENV NZBGET_GID         ${NZBGET_GID:-1000}

ARG NZBGET_PORT
ENV NZBGET_PORT        ${NZBGET_PORT:-80}

ARG NZBGET_SECUREPORT
ENV NZBGET_SECUREPORT  ${NZBGET_PORT:-443}
 
ARG NZBGET_VERSION
ENV NZBGET_VERSION     ${NZBGET_VERSION:-16.4}

ENV DOCKERIZE_VERSION  0.2.0
ENV DOCKERIZE_ARCH     {{.Env.DOCKERIZE_ARCH}}

ARG NZBGETGET_USERNAME
ENV NZBGET_USERNAME    ${NZBGET_USERNAME:-admin}

ARG NZBGET_PASSWORD
ENV NZBGET_PASSWORD    ${NZBGET_PASSWORD:-password}

 
ENV TERM xterm

RUN apk update
RUN apk add wget ca-certificates zsh vim libcap
RUN wget https://github.com/nzbget/nzbget/releases/download/v${NZBGET_VERSION}/nzbget-${NZBGET_VERSION}-bin-linux.run -O /tmp/nzbget.bin
RUN chmod a+x /tmp/nzbget.bin
RUN mkdir -p ${NZBGET_INSTALLDIR}
RUN /tmp/nzbget.bin --destdir ${NZBGET_INSTALLDIR} 

RUN wget https://github.com/jwilder/dockerize/releases/download/v${DOCKERIZE_VERSION}/dockerize-linux-${DOCKERIZE_ARCH}-v${DOCKERIZE_VERSION}.tar.gz -O /tmp/dockerize.tar.gz
RUN tar -C /usr/local/bin -xzvf /tmp/dockerize.tar.gz
RUN rm /tmp/dockerize.tar.gz

RUN addgroup -g ${NZBGET_GID} -S ${NZBGET_GROUP}
RUN adduser -G ${NZBGET_GROUP} -u ${NZBGET_UID} -S -H ${NZBGET_USER} 

RUN mkdir -p ${NZBGET_CONFDIR}
COPY ./files/nzbget.conf.tmpl ${NZBGET_CONFDIR}/nzbget.conf.tmpl
RUN chown -R ${NZBGET_USER}:${NZBGET_GROUP} ${NZBGET_CONFDIR}

RUN mkdir -p ${NZBGET_DATADIR}
RUN chown -R ${NZBGET_USER}:${NZBGET_GROUP} ${NZBGET_DATADIR}

RUN chown -R ${NZBGET_USER}:${NZBGET_GROUP} ${NZBGET_INSTALLDIR}

RUN setcap 'cap_net_bind_service=+ep' ${NZBGET_INSTALLDIR}/nzbget

VOLUME [${NZBGET_DATADIR}]
EXPOSE ${NZBGET_PORT} ${NZBGET_SECUREPORT}
USER ${NZBGET_USER}
WORKDIR ${NZBGET_INSTALLDIR} 

ENTRYPOINT ["zsh", "-c" , "dockerize -template ${NZBGET_CONFDIR}/nzbget.conf.tmpl:${NZBGET_CONFDIR}/nzbget.conf ./nzbget -c ${NZBGET_CONFDIR}/nzbget.conf -s"]